version: "3.9"

services:
  backend:
    image: prahlad8ac/rest:backend
    ports:
      - "5000:5000"
#    env_file:
#      - .env
    environment:
      - MONGO_URI=mongodb://mongo:27017/mydb
      - JWT_SECRET=5b7c24f4ec3d30c9f0f885c9c273428aa7c37052f6fc3e1f33a0f861d56a13a5c47eaf6f6a1fc1fd2d315c26d080e77d93d929b5569f3dbda07e54d2c0adbb4d
      - ACCESS_TOKEN_SECRET=aeac1d8c7fc548db86a17219831e9b942bfa3b1e843a8d0c3253a20a3a59211f5cfa0a9379cf1cdb4e34eb39e5c5cbdfd50dc14e788e38e294fa23c9e9ee663b
      - REFRESH_TOKEN_SECRET=3c9deaeeb8f60cbfd63cb36bc9c7740e0abdf8789993f50d6ccabc48b39f9e5196cc0c318d7a2c234126bdc9e0058a92ec92727d69bbf00e6e5f0b96e331e1d8
      - ACCESS_TOKEN_EXPIRY=15m
      - REFRESH_TOKEN_EXPIRY=10d
      - NODE_ENV=development
      - PORT=5000
      - CORS_ORIGIN=http://localhost:3000
      - USER_CORS_ORIGIN=http://localhost:5173
      - LH=http://localhost
# Use your actual credentials for these:
      - CLOUDINARY_CLOUD_NAME=dx0nsbrgg
      - CLOUDINARY_API_KEY=551252557164981
      - CLOUDINARY_API_SECRET=GeVuNGXFRPLJk6hUkwD6GiddBX8
      - SENDGRID_API_KEY=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
      - SENDGRID_VERIFIED_SENDER=prahladacharya45@gmail.com
#    secrets:
#      - backend_env
#   deploy:
#      replicas: 3
#      restart_policy:
#        condition: on-failure
#    command: sh -c "set -a && source /run/secrets/backend_env && npm start"
    healthcheck:
      test: ["CMD-SHELL", "wget -q --spider http://localhost:5000/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s

  frontend: 
    image: prahlad8ac/rest:frontend
    ports:
      - "3000:3000"

  user:
    image: prahlad8ac/rest:user
    ports:
      - "5173:5173"

  mongo:
    image: mongo:6.0-jammy
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - frontend
      - backend
      - user

#secrets:
#  backend_env:
#    external: true

volumes:
  mongo-data:
